biens/urls.py
from django.urls import path, re_path
from django.views.generic import TemplateView
from . import views

app_name = 'biens'
urlpatterns = [
    path('objets/', views.ObjetListView.as_view(), name='liste_objets'), 
    path('objets/<int:pk>/', views.ObjetDetailView.as_view(), name='detail_objet'),
    path('thumbnail/<int:objet_id>/', views.generate_thumbnail, name='generate_thumbnail'),
    path('tableau_bord/', views.TableauBordView.as_view(), name='tableau_bord'),
    path('encours/', views.page_encours, name='encours'),
    path('export-excel/', views.export_to_excel, name='export_to_excel'),
]

ged/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include
from django.urls import path
from django.views.generic import TemplateView
from biens import views as biens_views 
from django.conf.urls.static import static
from django.views import generic
from django.contrib.auth import views as auth_views
from photologue.sitemaps import GallerySitemap, PhotoSitemap


urlpatterns = [
    path('', biens_views.home, name='home'),
    path('objets/', include('biens.urls', namespace='objets')),
    path('documents/', include('papiers.urls', namespace='documents')),
    path('recettes/', include('recettes.urls', namespace='recettes')),
    path('photos/', include('photos.urls', namespace='photos')),
    path('admin/', admin.site.urls),
    path('grappelli/', include('grappelli.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('protected/', biens_views.ProtectedView.as_view(), name='protected'),
    path('photologue/', include('photologue.urls', namespace='photologue')),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitemaps = {
            'photologue_galleries': GallerySitemap,
            'photologue_photos': PhotoSitemap,
            }

papiers/urls.py
from django.urls import path, re_path
from django.views.generic import TemplateView
from . import views

app_name = 'papiers'
urlpatterns = [
    path('documents/', views.DocumentListView.as_view(), name='liste_documents'), 
    path('documents/<int:pk>/', views.DocumenttDetailView.as_view(), name='detail_document'),
    path('thumbnail/<int:document_id>/', views.generate_thumbnail, name='generate_thumbnail'),
    path('export-excel/', views.export_to_excel, name='export_to_excel'),
]

templates/documents/detail_document.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Détail document{% endblock %}
{% load custom_filters %}

{% block content %}
    
<div class="overflow-x-auto">
    <header class="bg-blue-600 text-white py-6 rounded-lg shadow-md">
        <div class="container mx-auto px-4 text-center">
          <h1 class="text-4xl font-extrabold tracking-wide">{{ document.document }}</h1>
        </div>
    </header>

    <table class="table-auto min-w-full bg-gray-100 border ">
        <tbody>
            <tr>
                <td><h3 class="text-xl font-bold text-blue-600">Document au format PDF</h3></td>
                <td>
                    {% if not document.url %}
                        <a href="{{ document.Document_pdf.url }}">
                            <img src="{% url 'documents:generate_thumbnail' document.id %}" alt="Miniature du PDF" class="w-64 max-w-xs sm:max-w-sm md:max-w-md object-cover rounded-xl">
                        </a>
                    {% else %}
                        <a href="{{ document.url }}">
                            <img src="{% static 'img/onedrive.jpg' %}" alt="OneDrive" class="w-64 max-w-xs sm:max-w-sm md:max-w-md object-cover rounded-xl">
                        </a>
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td class="border px-4 py-2 font-bold text-xl text-blue-600">Rubrique</td>
                <td class="border px-4 py-2 whitespace-normal">{{ document.rubrique }}</td>
            </tr>
            <tr>
                <td class="border px-4 py-2 font-bold text-xl text-blue-600">Type de document</td>
                <td class="border px-4 py-2 whitespace-normal">{{ document.type_document }}</td>
            </tr>
            <tr>
                <td class="border px-4 py-2 font-bold text-xl text-blue-600">Date de référence</td>
                <td class="border px-4 py-2 whitespace-normal">{{ document.date_reference }}</td>
            </tr>
            <tr>
                <td class="border px-4 py-2 font-bold text-xl text-blue-600">Commentaire</td>
                <td class="border px-4 py-2 whitespace-normal">{{ document.commentaire }}</td>
            </tr>
            <tr>
                <td class="border px-4 py-2 font-bold text-xl text-blue-600">Age du document</td>
                <td class="border px-4 py-2 whitespace-normal">
                    {{ document.age_document }} 
                    {% if document.age_document > 1 %} ans {% else %} an {% endif %}
                    {% if not document.type_document.permanente %}
                        sur {{ document.type_document.duree_conservation }}
                    {% endif %}
                    {% if document.type_document.permanente %}
                        <b>(à conserver en permanence)</b>
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td class="border px-4 py-2 font-bold">
                    {% if document.est_conserve %}
                        <p class="text-green-600 text-xl">Le document est encore dans la période de conservation.</p>
                    {% else %}
                        <p class="text-red-600 text-xl">Le document dépasse la période de conservation, vous pouvez le détruire.</p>
                    {% endif %}
                </td>
                <td class="border px-4 py-2 whitespace-normal">{{ document.type_document.precision }}</td>
            </tr>
        </tbody>
    </table>
</div>

{% endblock %}

templates/documents/liste_documents.html
{% extends 'base.html' %}
{% block title %}Liste des documents{% endblock %}
{% load custom_filters %}
{% load static %}

{% block content %}
<div class="container mx-auto px-4 py-6 bg-blue-600 rounded-lg shadow-md">
    <h1 class="text-3xl font-bold text-white text-center">📄 Liste des documents archivés</h1>
</div>

<div class="container mx-auto py-6">
    <div class="grid grid-cols-1 sm:grid-cols-2 gap-4 items-center">
        <a href="{% url 'documents:export_to_excel' %}" class="bg-green-600 text-white px-4 py-3 rounded-lg shadow-md hover:bg-green-700 transition flex items-center justify-center">
            Exporter <i class="fas fa-file-excel ml-2"></i>
        </a>

        <form method="GET" action="" class="flex items-center space-x-2 w-full sm:w-auto">
            <input class="flex-grow border border-gray-300 rounded-lg px-4 py-2 shadow focus:outline-none focus:ring focus:ring-blue-300" name="q" type="text" placeholder="🔍 Recherche" value="{{ request.GET.q }}">
            <button type="submit" class="px-4 py-2 bg-blue-600 text-white rounded-lg shadow-md hover:bg-blue-700 transition">
                <i class="fas fa-search"></i>
            </button>
        </form>
    </div>
</div>

<main class="container mx-auto px-4">
    <div class="overflow-x-auto bg-white rounded-lg shadow-md p-4">
        <table class="w-full text-sm text-left border-collapse">
            <thead class="bg-blue-600 text-white uppercase">
                <tr>
                    <th class="p-3 rounded-tl-lg">Document</th>
                    <th class="p-3">Rubrique</th>
                    <th class="p-3">Type</th>
                    <th class="p-3">Date</th>
                    <th class="p-3">Document</th>
                    <th class="p-3">Commentaire</th>
                    <th class="p-3 rounded-tr-lg">Conservation</th>
                </tr>
            </thead>
            <tbody>
                {% for document in documents %}
                <tr class="border-b hover:bg-gray-100 transition">
                    <td class="p-3 text-blue-600 underline">
                        <a href="{% url 'documents:detail_document' document.id %}">{{ document.document }}</a>
                    </td>
                    <td class="p-3">{{ document.rubrique }}</td>
                    <td class="p-3">{{ document.type_document }}</td>
                    <td class="p-3">{{ document.date_reference }}</td>
                    <td class="p-3">
                        {% if document.url %}
                            <a href="{{ document.url }}">
                                <img src="{% static 'img/onedrive.jpg' %}" alt="OneDrive" class="w-16 rounded-lg shadow-md">
                            </a>
                        {% else %}
                            <a href="{{ document.Document_pdf.url }}">
                                <img src="{% url 'documents:generate_thumbnail' document.id %}" alt="PDF" class="w-16 rounded-lg shadow-md">
                            </a>
                        {% endif %}
                    </td>
                    <td class="p-3">{{ document.commentaire }}</td>
                    <td class="p-3 text-green-600 font-bold">{{ document.est_conserve|yesno:"✅,❌" }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</main>

{% if is_paginated %}
<nav class="py-4 flex justify-center">
    {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}&q={{ request.GET.q }}" class="px-4 py-2 bg-gray-300 rounded-l-lg hover:bg-gray-400">&laquo;</a>
    {% endif %}
    <div class="px-4 py-2 bg-blue-600 text-white rounded-md">
        {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}
    </div>
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}&q={{ request.GET.q }}" class="px-4 py-2 bg-gray-300 rounded-r-lg hover:bg-gray-400">&raquo;</a>
    {% endif %}
</nav>
{% endif %}

{% endblock %}