biens/urls.py
from django.urls import path, re_path
from django.views.generic import TemplateView
from . import views

app_name = 'biens'
urlpatterns = [
    path('objets/', views.ObjetListView.as_view(), name='liste_objets'), 
    path('objets/<int:pk>/', views.ObjetDetailView.as_view(), name='detail_objet'),
    path('thumbnail/<int:objet_id>/', views.generate_thumbnail, name='generate_thumbnail'),
    path('tableau_bord/', views.TableauBordView.as_view(), name='tableau_bord'),
    path('encours/', views.page_encours, name='encours'),
    path('export-excel/', views.export_to_excel, name='export_to_excel'),
]

ged/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include
from django.urls import path
from django.views.generic import TemplateView
from biens import views as biens_views 
from django.conf.urls.static import static
from django.views import generic
from django.contrib.auth import views as auth_views
from photologue.sitemaps import GallerySitemap, PhotoSitemap


urlpatterns = [
    path('', biens_views.home, name='home'),
    path('objets/', include('biens.urls', namespace='objets')),
    path('documents/', include('papiers.urls', namespace='documents')),
    path('recettes/', include('recettes.urls', namespace='recettes')),
    path('photos/', include('photos.urls', namespace='photos')),
    path('admin/', admin.site.urls),
    path('grappelli/', include('grappelli.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('protected/', biens_views.ProtectedView.as_view(), name='protected'),
    path('photologue/', include('photologue.urls', namespace='photologue')),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitemaps = {
            'photologue_galleries': GallerySitemap,
            'photologue_photos': PhotoSitemap,
            }

papiers/urls.py
from django.urls import path, re_path
from django.views.generic import TemplateView
from . import views

app_name = 'papiers'
urlpatterns = [
    path('documents/', views.DocumentListView.as_view(), name='liste_documents'), 
    path('documents/<int:pk>/', views.DocumenttDetailView.as_view(), name='detail_document'),
    path('thumbnail/<int:document_id>/', views.generate_thumbnail, name='generate_thumbnail'),
    path('export-excel/', views.export_to_excel, name='export_to_excel'),
]

photos/urls.py
from django.urls import path, re_path
from django.views.generic import TemplateView
from . import views

app_name = 'photos'
urlpatterns = [
    path('galleries/', views.GalleryListView.as_view(), name="gallery_list"),
    path('galleries/<slug:slug>/', views.GalleryDetailView.as_view(), name="gallery_detail"),
    path('listePhotos/',views.PhotoListView.as_view(), name="photo_list"),
    path('photos/<int:pk>/', views.PhotoDetailView.as_view(), name="photo_detail"),
]

recettes/urls.py
from django.contrib import admin
from django.urls import path
from recettes import views

app_name = 'recettes'
urlpatterns = [
    path('', views.RecetteListView.as_view(), name='recettes'),
    path('<int:pk>/', views.RecetteDetailView.as_view(), name='detail'),
    path('<int:pk>/export-docx/', views.ExportRecetteDocxView.as_view(), name='export_docx'),
    path("<int:pk>/pdf/", views.ExportRecettePDFView.as_view(), name="recette_pdf"),
    path('new/', views.RecetteCreateView.as_view(), name='recette_create'),
    path('<int:pk>/edit/', views.RecetteUpdateView.as_view(), name='recette_update'),

]

templates/Encours_construction.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container mx-auto px-4">
    <div class="flex justify-center items-center">
        <div class="w-full">
            <h1 class="text-center text-3xl text-gray-900">Cette page est en cours de construction</h1>
        </div>
    </div>

    <div class="flex justify-center mt-6">
        <div class="text-center">
            <img src="{% static 'img/construction.jpg' %}" alt="Travaux" class="w-72 h-72">
        </div>
    </div>
</div>

{% endblock %}

templates/Gallery.html
<!--liste_objet.html-->
{% extends 'base.html' %}
{% block title %}Mes photos{% endblock %}
{% load custom_filters %}
{% block content %}
{% for gallery in galleries %}
<h2 class="text-primary">{{ gallery.title }}</h2>
<p>{{ gallery.description }}</p>
{% for photo in gallery.public %}
    <img src="{{ photo.get_display_url }}" alt="{{ photo.title }}">
{% endfor %}
{% endfor %}
{% endblock %}


	

templates/base.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdn.jsdelivr.net/npm/sortablejs@1.15.0/Sortable.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/objet-style.css' %}" />
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon.png' %}">
    <link rel="apple-touch-icon" href="{% static 'img/favicon.png' %}">
    <title>{% block title %}Portail AB{% endblock %}</title>
    <style>
        @media print {
          /* Cacher les éléments inutiles lors de l'impression */
          iframe, button, nav{
            display: none !important;
          }
      
          /* Optimisation du contenu principal pour l'impression */
          body,.container {
            margin: 0;
            padding: 0;
            width: 100%;
          }
      
          /* Styles spécifiques pour les éléments imprimés */
          body {
            font-size: 14px;
            color: #000;
          }
          
          /* Améliorer la lisibilité pour les sections */
          section {
            page-break-inside: avoid;
            margin-bottom: 0px;
          }
         
        img {
            max-width: 100%;
            height: auto;
            object-fit: contain;
            }
        }
        /* Chrome, Safari, Edge */
        input[type=number]::-webkit-inner-spin-button,
        input[type=number]::-webkit-outer-spin-button {
        -webkit-appearance: none;
        margin: 0;
           }

        /* Firefox */
        input[type=number] {
        -moz-appearance: textfield;
        }
        input[name$="-ordre"] { display: none; }
        .ingredient-row {
            transition: opacity .2s ease;
        }
        #id_etapes {
                  background: transparent;
                  position: relative;
                  z-index: 10;
                }
      </style>
</head>
{% block extra_js %}{% endblock %}
<body class="bg-gray-100">
  <header>
    <nav class="bg-blue-500 text-white text-lg font-bold py-3">
    <div class="container mx-auto flex items-center justify-between px-4">
        <div class="flex items-center space-x-3">
            <a href="{% url 'home' %}" class="flex items-center">
                <img
                    src="{% static 'img/favicon.png' %}"
                    class="h-11 w-11 rounded-xl shadow-sm bg-white p-1"
                >
            </a>
            <a class="text-lg font-bold flex items-center" href="{% url 'home' %}">
                <i class="fas fa-home"></i>
            </a>
        </div>

        <!-- Bouton menu mobile -->
        <button id="menuToggle" class="lg:hidden text-white focus:outline-none">
            <span class="fas fa-bars"></span>
        </button>

        <!-- Menu Responsive -->
        <div id="menu" class="hidden flex flex-col lg:flex lg:flex-row lg:space-x-4 lg:relative lg:top-0 lg:w-auto absolute top-14 left-0 w-full bg-blue-500 text-white shadow-md py-2 lg:py-0">
            <a class="py-2 px-4 hover:bg-blue-600 block rounded-lg" href="{% url 'objets:tableau_bord' %}">📊 Tableau de Bord</a>
            <a class="py-2 px-4 hover:bg-blue-600 block rounded-lg" href="{% url 'objets:liste_objets' %}">🛍️ Objets</a>
            <a class="py-2 px-4 hover:bg-blue-600 block rounded-lg" href="{% url 'documents:liste_documents' %}">📄 Documents</a>
    
          <!-- Sous-menu Photos -->
            <div class="relative group flex items-center">
                    <a class="py-2 px-4 hover:bg-blue-600 block rounded-lg cursor-pointer" id="navbarDropdown2" href="#" role="button">
                        📷 Photos ⬇
                    </a>
                    <ul class="absolute hidden group-hover:block bg-white text-gray-800 shadow-lg rounded-md mt-28 w-56">
                        <li><a class="block px-4 py-2 hover:bg-gray-100" href="{% url 'photos:gallery_list' %}">🏞️ Galeries</a></li>
                        <li><a class="block px-4 py-2 hover:bg-gray-100" href="{% url 'photos:photo_list' %}">📷 Toutes les photos</a></li>
                    </ul>
            </div>

            <a class="py-2 px-4 hover:bg-blue-600 block rounded-lg" href="{% url 'recettes:recettes' %}">🍽️ Cuisine</a>
            <a class="py-2 px-4 hover:bg-blue-600 block rounded-lg" href="{% url 'admin:index' %}" target="_blank">⚙️ Gestion des données</a>       
        </div>

        <!-- Profil utilisateur -->
        <div class="flex items-center space-x-4">
            <div class="text-white font-bold">{{ user.username }}</div>
            <div class="relative group">
                <a class="text-white hover:text-gray-300" id="navbarDropdown" href="#" role="button">
                    <i class="fas fa-user fa-fw"></i>
                </a>
                <ul class="absolute right-0 mt-2 w-48 bg-white shadow-lg rounded-md opacity-0 group-hover:opacity-100 transition-opacity">
                    <li><a href="{% url 'login' %}" class="block px-4 py-2 text-gray-700 hover:bg-gray-100">Se connecter</a></li>
                    <li>
                        <form method="post" action="{% url 'logout' %}">
                            {% csrf_token %}
                            <button type="submit" class="block w-full text-left px-4 py-2 text-gray-700 hover:bg-gray-100">Se déconnecter</button>
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>

 </header>

<main class="container mx-auto p-4">
    {% block content %}
    {% endblock %}
</main>

<footer class="text-center py-4 bg-gray-200 mt-8">
    <p>© 2026 ABSite.fr</p>
</footer>

<script src="{% static 'js/fontawesome-all.min.js' %}"></script>
<script>
document.getElementById("add-ingredient").addEventListener("click", function () {
    const totalFormsInput = document.querySelector(
        'input[name="ingredients-TOTAL_FORMS"]'
    );

    const index = parseInt(totalFormsInput.value, 10);
    const template = document.getElementById("ingredient-empty-form").innerHTML;

    const html = template.replace(/__prefix__/g, index);

    document.getElementById("ingredient-list")
        .insertAdjacentHTML("beforeend", html);

    totalFormsInput.value = index + 1;
});
    const list = document.getElementById("ingredient-list");

new Sortable(list, {
    handle: ".cursor-move",
    animation: 150,
    onEnd: function () {
        document
            .querySelectorAll("#ingredient-list input[name$='-ordre']")
            .forEach((input, index) => {
                input.value = index;
            });
    }
});
</script>
<script>
<script>
document.addEventListener("click", function (e) {
    if (e.target.classList.contains("delete-ingredient")) {
        const row = e.target.closest(".ingredient-row");

        // coche DELETE
        const deleteInput = row.querySelector("input[name$='-DELETE']");
        if (deleteInput) {
            deleteInput.checked = true;
        }

        // masque visuellement
        row.style.display = "none";

        // recalcule l’ordre
        updateOrdre();
    }
});

function updateOrdre() {
    document
        .querySelectorAll(
            "#ingredient-list .ingredient-row:not([style*='display: none']) input[name$='-ordre']"
        )
        .forEach((input, index) => {
            input.value = index;
        });
}
row.style.opacity = 0.4;

</script>
</body>
</html>

templates/create_bien.html
{% extends 'base.html' %}

{% block title %}Créer un Bien{% endblock %}

{% block content %}
<h1>Créer un Bien Boostrap 5</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="button" class="btn btn-primary">Enregistrer</button>
</form>
{% endblock %}

templates/detail_objet.html
<!-- detail_objet.html -->

{% extends 'base.html' %}
{% block title %}Détail objet{% endblock %}
{% load custom_filters %}

{% block content %}
    <div class="max-w-7xl mx-auto px-4">
        <div class="flex justify-center items-center">
            <h1 class="text-center bg-gray-100 text-3xl font-bold p-4 rounded-md">{{ objet.name }}</h1>
        </div>

        <div class="overflow-x-auto mt-6">
            <table class="min-w-full bg-gray-100 border border-gray-300">
                <tbody>
                    <tr>
                        <td class="border px-4 py-2">
                            <a href="{{ objet.photo.url }}">
                                <img src="{{ objet.photo.url }}" alt="{{ objet.name }}" class="w-96 h-auto object-cover rounded-xl">
                            </a>
                        </td>
                        <td class="border px-4 py-2">
                            <a href="{{ objet.document.url }}">
                                <img src="{% url 'objets:generate_thumbnail' objet.id %}" alt="Miniature du PDF" class="w-auto h-96 object-cover rounded-xl">
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <td class="border px-4 py-2 font-bold">Rubrique contrat assurance</td>
                        <td class="border px-4 py-2">{{ objet.rubrique }}</td>
                    </tr>
                    <tr>
                        <td class="border px-4 py-2 font-bold">Catégorie du bien</td>
                        <td class="border px-4 py-2">{{ objet.categorie }}</td>
                    </tr>
                    <tr>
                        <td class="border px-4 py-2 font-bold">Pièce</td>
                        <td class="border px-4 py-2">{{ objet.piece }}</td>
                    </tr>
                    <tr>
                        <td class="border px-4 py-2 font-bold">Date de l'achat</td>
                        <td class="border px-4 py-2">{{ objet.achat_at }}</td>
                    </tr>
                    <tr>
                        <td class="border px-4 py-2 font-bold">Prix d'achat ou estimé</td>
                        <td class="border px-4 py-2">{{ objet.montant|format_currency }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% comment %} <div class="container mx-full p-3 bg-red-400 rounded-2xl">
    <div class="flex justify-center">
        <h1 class="text-4xl font-bold text-center text-white shadow-3xl">L'accès aux pages de ce site est réservé aux personnes autorisées.</h1>
    </div>
</div> {% endcomment %}

<section class="min-h-screen flex items-center justify-center bg-gray-100">

    <div class="container mx-auto px-4 bg-image bg-cover bg-center rounded-lg shadow-lg">
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 p-4">

            <!-- Cadre 1 -->
            <div class="bg-blue-50 rounded-lg shadow-lg overflow-hidden">
                <img src="{% static 'img/objets.png' %}" alt="Objets" class="w-full h-auto object-cover">
                <div class="p-4 text-center">
                    <a href="{% url 'objets:liste_objets' %}" class="text-lg font-bold text-blue-500 hover:underline">
                        Mobilier et objets de valeur présents dans l'appartement
                    </a>
                </div>
            </div>

            <!-- Cadre 2 -->
            <div class="bg-blue-50 rounded-lg shadow-lg overflow-hidden">
                <img src="{% static 'img/documents.png' %}" alt="Documents" class="w-full h-auto object-cover">
                <div class="p-4 text-center">
                    <a href="{% url 'documents:liste_documents' %}" class="text-lg font-bold text-blue-500 hover:underline">
                        Documents à conserver
                    </a>
                </div>
            </div>

            <!-- Cadre 3 -->
            <div class="bg-blue-50 rounded-lg shadow-lg overflow-hidden">
                <img src="{% static 'img/photos.png' %}" alt="Galeries Photos" class="w-full h-auto object-cover">
                <div class="p-4 text-center">
                    <a href="{% url 'photos:gallery_list' %}" class="text-lg font-bold text-blue-500 hover:underline">
                        Galeries de photos
                    </a>
                </div>
            </div>

            <!-- Cadre 4 -->
            <div class="bg-blue-50 rounded-lg shadow-lg overflow-hidden">
                <img src="{% static 'img/recettes.png' %}" alt="Recettes" class="w-full h-auto object-cover">
                <div class="p-4 text-center">
                    <a href="{% url 'recettes:recettes' %}" class="text-lg font-bold text-blue-500 hover:underline">
                        Recettes de cuisine
                    </a>
                </div>
            </div>

        </div>
    </div>

</section>

{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container mx-auto px-4 flex justify-center items-center">
    <div class="max-w-md w-full bg-white p-6 rounded-lg shadow-lg">
        <h2 class="text-center text-2xl font-bold text-gray-700">Veuillez vous connecter</h2>
        <form method="post" class="mt-4">
            {% csrf_token %}
            <div class="space-y-4">
                <div>
                    <label class="block text-gray-600 font-medium">{{ form.username.label_tag }}</label>
                    {{ form.username }}
                </div>
                <div>
                    <label class="block text-gray-600 font-medium">{{ form.password.label_tag }}</label>
                    {{ form.password }}
                </div>
                <div class="flex justify-end">
                    <button type="submit" class="w-full bg-blue-500 text-white px-4 py-2 rounded-lg hover:bg-blue-600 transition duration-200">
                        Se connecter
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}

templates/protected.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<body>
    <div class="container mx-auto px-4">
        <h1 class="text-center text-lg font-semibold">Bienvenue sur les pages protégées</h1>
        <h2 class="text-red-600 text-center">Seuls les utilisateurs authentifiés peuvent voir ces pages.</h2>
    </div>
</body>

{% endblock %}

templates/tableau_bord.html
{% extends 'base.html' %}
{% block title %}Répartition Contrat Assurance{% endblock %}
{% load custom_filters %}
{% load static %}

{% block content %}
<!-- En-tête modernisé -->
<div class="container mx-auto px-4 py-6 bg-blue-600 rounded-lg shadow-md">
    <h1 class="text-4xl font-bold text-white text-center">📊 Tableau de bord</h1>
</div>

<!-- Section principale -->
<div class="container mx-auto px-4 mt-6">
    <div class="flex flex-wrap">
        <!-- Tableau principal -->
        <div class="w-full md:w-7/12 overflow-x-auto">
            <h2 class="text-center text-xl font-semibold mb-4 text-gray-900 bg-clip-text text-transparent bg-gradient-to-r from-green-400 to-purple-500">
                Répartition contrat assurance
            </h2>
        
            <div class="bg-white shadow-md rounded-lg overflow-x-auto p-4">
                <table class="w-full text-sm border-collapse">
                    <thead class="bg-blue-600 text-white uppercase">
                        <tr>
                            <th class="p-3">Rubrique</th>
                            <th class="p-3">Couverture</th>
                            <th class="p-3">Montant consommé</th>
                            <th class="p-3">Montant restant</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for rubrique in rubriques %}
                        <tr class="border-b hover:bg-gray-100 transition">
                            <td class="p-3 whitespace-nowrap">{{ rubrique.name }}</td>
                            <td class="p-3 whitespace-nowrap">{{ rubrique.montant_assu|format_currency }}</td>
                            <td class="p-3 whitespace-nowrap">{{ rubrique.total_montant|format_currency }}</td>
                            <td class="p-3 whitespace-nowrap {% if rubrique.montant_assu|subtract:rubrique.total_montant < 0 %}text-red-600{% else %}text-green-600{% endif %}">
                                <b>{{ rubrique.montant_assu|subtract:rubrique.total_montant|format_currency }}</b>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        

        <!-- Graphique -->
        <div class="w-full md:w-5/12 flex justify-center mt-6 md:mt-0">
            <img src="data:image/png;base64,{{ barchart }}" alt="Graphique à Barres" class="w-full md:w-96 h-auto rounded-2xl shadow-md">
        </div>
    </div>
</div>

<!-- Répartition par pièce -->
<div class="container mx-auto px-4 mt-12">
    <h2 class="text-center text-xl font-semibold mb-4 text-gray-900 bg-clip-text text-transparent bg-gradient-to-r from-green-400 to-purple-500">
        Répartition par pièce de l'appartement
    </h2>

    <div class="bg-white shadow-md rounded-lg overflow-x-auto p-4">
        <table class="w-full text-sm border-collapse">
            <thead class="bg-blue-600 text-white uppercase">
                <tr>
                    <th class="p-3">Pièce</th>
                    <th class="p-3">Total pièce</th>
                </tr>
            </thead>
            <tbody>
                {% for piece in pieces %}
                <tr class="border-b hover:bg-gray-100 transition">
                    <td class="p-3">{{ piece.piece }}</td>
                    <td class="p-3 text-right">{{ piece.total_montant|format_currency }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<!-- Répartition par catégorie -->
<div class="container mx-auto px-4 mt-12">
    <h2 class="text-center text-xl font-semibold mb-4 text-gray-900 bg-clip-text text-transparent bg-gradient-to-r from-green-400 to-purple-500">
        Répartition par catégorie
    </h2>

    <div class="bg-white shadow-md rounded-lg overflow-x-auto p-4">
        <table class="w-full text-sm border-collapse">
            <thead class="bg-blue-600 text-white uppercase">
                <tr>
                    <th class="p-3">Catégorie</th>
                    <th class="p-3">Total catégorie</th>
                </tr>
            </thead>
            <tbody>
                {% for categorie in categories %}
                <tr class="border-b hover:bg-gray-100 transition">
                    <td class="p-3">{{ categorie.categorie__name }}</td>
                    <td class="p-3 text-right">{{ categorie.total_montant|format_currency }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}