biens/urls.py
from django.urls import path, re_path
from django.views.generic import TemplateView
from . import views

app_name = 'biens'
urlpatterns = [
    path('objets/', views.ObjetListView.as_view(), name='liste_objets'), 
    path('objets/<int:pk>/', views.ObjetDetailView.as_view(), name='detail_objet'),
    path('thumbnail/<int:objet_id>/', views.generate_thumbnail, name='generate_thumbnail'),
    path('tableau_bord/', views.TableauBordView.as_view(), name='tableau_bord'),
    path('encours/', views.page_encours, name='encours'),
    path('export-excel/', views.export_to_excel, name='export_to_excel'),
]

ged/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include
from django.urls import path
from django.views.generic import TemplateView
from biens import views as biens_views 
from django.conf.urls.static import static
from django.views import generic
from django.contrib.auth import views as auth_views
from photologue.sitemaps import GallerySitemap, PhotoSitemap


urlpatterns = [
    path('', biens_views.home, name='home'),
    path('objets/', include('biens.urls', namespace='objets')),
    path('documents/', include('papiers.urls', namespace='documents')),
    path('recettes/', include('recettes.urls', namespace='recettes')),
    path('photos/', include('photos.urls', namespace='photos')),
    path('admin/', admin.site.urls),
    path('grappelli/', include('grappelli.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('protected/', biens_views.ProtectedView.as_view(), name='protected'),
    path('photologue/', include('photologue.urls', namespace='photologue')),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitemaps = {
            'photologue_galleries': GallerySitemap,
            'photologue_photos': PhotoSitemap,
            }

templates/objets/detail_objet.html
<!-- detail_objet.html -->
{% extends 'base.html' %}
{% block title %}Détail objet{% endblock %}
{% load custom_filters %}

{% block content %}
    <div class="container mx-auto px-4 max-w-7xl">
      
        <header class="bg-blue-600 text-white py-6 rounded-lg shadow-md">
            <div class="container mx-auto px-4 text-center">
              <h1 class="text-4xl font-extrabold tracking-wide">{{ objet.name }}</h1>
            </div>
        </header>



        <div class="overflow-x-auto mt-6">
            <table class="table-auto w-full bg-gray-100 border border-gray-300">
                <tbody>
                    <tr>
                        <td class="border px-4 py-2">
                            <a href="{{ objet.photo.url }}">
                                <img src="{{ objet.photo.url }}" alt="{{ objet.name }}" class="w-full max-w-md object-cover rounded-xl">
                            </a>
                        </td>
                        <td class="border px-4 py-2">
                            <a href="{{ objet.document.url }}">
                                <img src="{% url 'objets:generate_thumbnail' objet.id %}" alt="Miniature du PDF" class="w-full max-w-xs sm:max-w-sm md:max-w-md object-cover rounded-xl">
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <td class="border text-xl px-4 py-2 font-bold text-blue-600">Rubrique contrat assurance</td>
                        <td class="border px-4 py-2 whitespace-normal">{{ objet.rubrique }}</td>
                    </tr>
                    <tr>
                        <td class="border px-4 py-2 font-bold text-xl text-blue-600">Catégorie du bien</td>
                        <td class="border px-4 py-2 whitespace-normal">{{ objet.categorie }}</td>
                    </tr>
                    <tr>
                        <td class="border px-4 py-2 font-bold text-xl text-blue-600">Pièce</td>
                        <td class="border px-4 py-2 whitespace-normal">{{ objet.piece }}</td>
                    </tr>
                    <tr>
                        <td class="border px-4 py-2 font-bold text-xl  text-blue-600">Date de l'achat</td>
                        <td class="border px-4 py-2 whitespace-normal">{{ objet.achat_at }}</td>
                    </tr>
                    <tr>
                        <td class="border px-4 py-2 font-bold text-xl text-blue-600">Prix d'achat ou estimé</td>
                        <td class="border px-4 py-2 whitespace-normal">{{ objet.montant|format_currency }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/objets/liste_objets.html
{% extends 'base.html' %}
{% block title %}Liste Objets{% endblock %}
{% load custom_filters %}

{% block content %}
<!-- En-tête modernisé -->
<div class="container mx-auto px-4 py-6 bg-blue-600 rounded-lg shadow-md">
    <h1 class="text-3xl font-bold text-white text-center">🛍️ Liste des objets toujours présents</h1>
</div>

<!-- Boutons et Recherche -->
<div class="container mx-auto py-6">
    <div class="grid grid-cols-1 sm:grid-cols-2 gap-4 items-center">
        <a href="{% url 'objets:export_to_excel' %}" class="bg-green-600 text-white px-4 py-3 rounded-lg shadow-md hover:bg-green-700 transition flex items-center justify-center">
            Exporter <i class="fas fa-file-excel ml-2"></i>
        </a>

        <form method="GET" action="" class="flex items-center space-x-2 w-full sm:w-auto">
            <input class="flex-grow border border-gray-300 rounded-lg px-4 py-2 shadow focus:outline-none focus:ring focus:ring-blue-300" name="q" type="text" placeholder="🔍 Recherche" value="{{ request.GET.q }}">
            <button type="submit" class="px-4 py-2 bg-blue-600 text-white rounded-lg shadow-md hover:bg-blue-700 transition">
                <i class="fas fa-search"></i>
            </button>
        </form>
    </div>
</div>

<!-- Tableau responsive -->
<main class="container mx-auto px-4">
    <div class="overflow-x-auto bg-white rounded-lg shadow-md p-4">
        <table class="w-full text-sm text-left border-collapse">
            <thead class="bg-blue-600 text-white uppercase">
                <tr>
                    <th class="p-3 rounded-tl-lg">Photo</th>
                    <th class="p-3">Description</th>
                    <th class="p-3">Assurance</th>
                    <th class="p-3">Catégorie</th>
                    <th class="p-3">Pièce</th>
                    <th class="p-3">Prix</th>
                    <th class="p-3 rounded-tr-lg">Date Achat</th>
                </tr>
            </thead>
            <tbody>
                {% for objet in objets %}
                <tr class="border-b hover:bg-gray-100 transition">
                 
                    <td class="p-3 text-center">
                        <a href="{% url 'objets:detail_objet' objet.id %}">
                            <img src="{{ objet.photo.url }}" alt="{{ objet.name }}" class="w-16 rounded-lg shadow-md">
                        </a>
                    </td>
                    <td class="p-3">
                         <a href="{% url 'objets:detail_objet' objet.id %}">
                        {{ objet.name }}
                        </a>
                    </td>
                    <td class="p-3">{{ objet.rubrique }}</td>
                    <td class="p-3">{{ objet.categorie }}</td>
                    <td class="p-3">{{ objet.piece }}</td>
                    <td class="p-3 font-bold text-green-600">{{ objet.montant|format_currency }}</td>
                    <td class="p-3">{{ objet.achat_at }}</td>
                   
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</main>

<!-- Pagination -->
{% if is_paginated %}
<nav class="py-4 flex justify-center">
    {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}&q={{ request.GET.q }}" class="px-4 py-2 bg-gray-300 rounded-l-lg hover:bg-gray-400">&laquo;</a>
    {% endif %}
    <div class="px-4 py-2 bg-blue-600 text-white rounded-md">
        {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}
    </div>
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}&q={{ request.GET.q }}" class="px-4 py-2 bg-gray-300 rounded-r-lg hover:bg-gray-400">&raquo;</a>
    {% endif %}
</nav>
{% endif %}

{% endblock %}