ged/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include
from django.urls import path
from django.views.generic import TemplateView
from biens import views as biens_views 
from django.conf.urls.static import static
from django.views import generic
from django.contrib.auth import views as auth_views
from photologue.sitemaps import GallerySitemap, PhotoSitemap


urlpatterns = [
    path('', biens_views.home, name='home'),
    path('objets/', include('biens.urls', namespace='objets')),
    path('documents/', include('papiers.urls', namespace='documents')),
    path('recettes/', include('recettes.urls', namespace='recettes')),
    path('photos/', include('photos.urls', namespace='photos')),
    path('admin/', admin.site.urls),
    path('grappelli/', include('grappelli.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('protected/', biens_views.ProtectedView.as_view(), name='protected'),
    path('photologue/', include('photologue.urls', namespace='photologue')),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitemaps = {
            'photologue_galleries': GallerySitemap,
            'photologue_photos': PhotoSitemap,
            }

photos/urls.py
from django.urls import path, re_path
from django.views.generic import TemplateView
from . import views

app_name = 'photos'
urlpatterns = [
    path('galleries/', views.GalleryListView.as_view(), name="gallery_list"),
    path('galleries/<slug:slug>/', views.GalleryDetailView.as_view(), name="gallery_detail"),
    path('listePhotos/',views.PhotoListView.as_view(), name="photo_list"),
    path('photos/<int:pk>/', views.PhotoDetailView.as_view(), name="photo_detail"),
]

photos/models.py
from django.db import models

# Create your models here.

photos/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from django.views.generic import DetailView

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from photologue.models import Gallery
from photologue.models import Photo

from django.views.generic import ListView
class GalleryListView(LoginRequiredMixin, PermissionRequiredMixin,ListView):
    model = Gallery
    template_name = "photos/gallery_list.html"  #
    context_object_name = "galleries"
    permission_required = 'photologue.view_gallery'
    permission_denied_message = "Vous n'avez pas la permission de voir cette page."

    def get_queryset(self):
        return Gallery.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        for gallery in context["galleries"]:
            gallery.main_photo = gallery.photos.first()  # Définit la première photo
        return context


class GalleryDetailView(DetailView):
    model = Gallery
    template_name = "photos/gallery_detail.html"
    context_object_name = "gallery"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["photos"] = self.object.photos.all()  # Liste des photos
        return context

class PhotoDetailView(DetailView):
    model = Photo
    template_name = "photos/photo_detail.html"
    context_object_name = "photo"

class PhotoListView(ListView):
    model = Photo
    template_name = "photos/photo_list.html"
    context_object_name = "photos"

    def get_queryset(self):
        query = self.request.GET.get("q")
        photos = Photo.objects.all()
        if query:
            photos = photos.filter(title__icontains=query)
        return photos

templates/photos/gallery_detail.html
{% extends 'base.html' %}
{% block title %}Mes photos{% endblock %}
{% load custom_filters %}

{% block content %}
<header class="bg-blue-600 text-white py-6 rounded-lg shadow-md">
    <div class="container mx-auto px-4 text-center">
      <h1 class="text-4xl font-extrabold tracking-wide">Détail de la Galerie</h1>
    </div>
</header>

<div class="w-full mx-auto text-center md:w-11/12 xl:w-9/12">
    <h1 class="mb-6 text-4xl font-extrabold leading-none tracking-tight text-gray-900 md:text-4xl bg-clip-text text-transparent bg-gradient-to-r from-green-400 to-purple-500">
        {{ gallery.title }}
    </h1>
</div>

    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
        {% for photo in photos %}
        <div class="bg-white rounded-lg shadow-lg overflow-hidden transform hover:scale-105 transition duration-500">
            <a href="{% url 'photos:photo_detail' photo.pk %}" class="block">
                <img src="{{ photo.image.url }}" alt="{{ photo.title }}" class="w-full h-72 object-contain object-top">   
            </a>
            <div class="p-4">
                <h3 class="text-lg font-semibold text-blue-600">{{ photo.title }}</h3>
                <p class="text-sm text-gray-500">{{ photo.description }}</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/photos/gallery_list.html
{% extends 'base.html' %}
{% block title %}Mes photos{% endblock %}
{% load custom_filters %}

{% block content %}
<!-- En-tête modernisé -->
<div class="container mx-auto px-4 py-6 bg-blue-600 rounded-lg shadow-md">
    <h1 class="text-4xl font-bold text-white text-center">📷 Galeries de Photos</h1>
</div>

<!-- Titre principal avec effet -->
<div class="w-full mx-auto text-center md:w-11/12 xl:w-9/12">
    <h1 class="mb-6 text-4xl font-extrabold leading-none tracking-tight text-gray-900 md:text-5xl bg-clip-text text-transparent bg-gradient-to-r from-green-400 to-purple-500">
        Voici les plus belles prises 📸
    </h1>
</div>

<!-- Grille adaptative des galeries -->
<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 container mx-auto p-6">
    {% for gallery in galleries %}
    <div class="bg-white rounded-xl shadow-lg p-4 transform hover:scale-105 transition duration-300">
         <a href="{% url 'photos:gallery_detail' gallery.slug %}" class="block">
        <img class="w-full h-64 object-cover rounded-lg shadow-md" src="{{ gallery.main_photo.image.url }}" alt="{{ gallery.title }}">
        </a>
        <div class="mt-4 text-center">
            <h3 class="text-blue-600 text-2xl font-bold">{{ gallery.title }}</h3>
            <p class="mt-3 text-gray-700 text-sm">{{ gallery.description }}</p>
            <a href="{% url 'photos:gallery_detail' gallery.slug %}" class="inline-block bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-xl transition mt-4">
                Voir les photos 🔍
            </a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/photos/photo_detail.html
{% extends 'base.html' %}
{% block title %}Mes photos{% endblock %}
{% load custom_filters %}

{% block content %}
<div class="container mx-auto px-6 py-6 flex flex-col items-center">
    <img src="{{ photo.image.url }}" alt="{{ photo.title }}" class="w-full max-w-3xl h-auto rounded-lg shadow-lg transform hover:scale-105 transition duration-300">
    
    <h1 class="text-2xl font-bold text-blue-600 mt-8">{{ photo.title }}</h1>

    <a href="{{ photo.image.url }}" download 
    class="inline-block bg-green-600 text-white px-6 py-3 rounded-md shadow hover:bg-green-700 transition">
    Télécharger l'image <i class="fas fa-download"></i>
    </a>
</div>
{% endblock %}

templates/photos/photo_list.html
{% extends 'base.html' %}
{% block title %}Galerie de Photos{% endblock %}

{% block content %}
<div class="container mx-auto px-6 py-6">
    <div class="container mx-auto px-4 py-6 bg-blue-600 rounded-lg shadow-md">
    <h1 class="text-4xl font-bold text-white text-center">📷 Toutes les Photos</h1>
    </div>

    <!-- Barre de recherche -->
    <div class="flex flex-col md:flex-row justify-end mt-6 mb-6">
    <form method="GET" action="" class="flex flex-wrap items-center space-x-2">
        <input class="border border-gray-300 rounded-xl px-4 py-2 shadow-md w-full md:w-auto focus:ring focus:ring-blue-300" name="q" type="text" placeholder="🔍 Rechercher..." value="{{ request.GET.q }}">
        <button type="submit" class="px-4 py-2 bg-blue-600 text-white rounded-lg shadow-md hover:bg-blue-700 transition">
            <i class="fas fa-search"></i>
        </button>
    </form>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {% for photo in photos %}
            <div class="bg-white rounded-lg shadow-lg overflow-hidden transform hover:scale-105 transition duration-500">
            <a href="{% url 'photos:photo_detail' photo.pk %}" class="block">
                <img src="{{ photo.image.url }}" alt="{{ photo.title }}" class="w-full h-72 object-contain object-top rounded-md">   
            </a>
            <div class="p-4">
                <h3 class="text-lg font-semibold text-blue-600">{{ photo.title }}</h3>
                <p class="text-sm text-gray-500">{{ photo.description }}</p>
            </div>
        </div>
        {% empty %}
        <p class="text-center text-gray-500 text-lg">Aucune photo trouvée.</p>
        {% endfor %}
    </div>
</div>
{% endblock %}